# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b889e2c31e18d5a0b100346d55dfc5e8378abccd5ac4fc656f3092cc9738b7a56d30dd28727c3eb3018be212a2c385e3e63136e480c1e45bdfcd6df6c2a4e1a

test:
  secret_key_base: 4634d540580c095a9ef122ceecf04356e5bed4ac023e08f259dbb7c6211c471d22736eaacbf689cedcf181409e90991643455cc1fd5724e6f5ae96a329a94559

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
